version: "3.8"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    restart: unless-stopped
    container_name: es8
    environment:
      xpack.security.enabled: "false"
      xpack.security.enrollment.enabled: "false"
      bootstrap.memory_lock: "true"
      discovery.type: single-node
    deploy:
      resources:
        limits:
          memory: 4G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - db-network

volumes:
  es-data:
    external: true

networks:
  db-network:
    external: true
